<?php

return [
    'theme' => 'caption-light',
    'default_locale' => 'en',
    'languages' => [
        'en' => ['label' => 'English', 'flag' => 'gb', 'flag_overrides' => ['us' => 'us', 'ca' => 'us', 'au' => 'au', 'nz' => 'nz', 'in' => 'in']],
        'de' => ['label' => 'Deutsch', 'flag' => 'de'],
        'es' => ['label' => 'Español', 'flag' => 'es'],
        'fr' => ['label' => 'Français', 'flag' => 'fr'],
        'pt-br' => ['label' => 'Português (BR)', 'flag' => 'br'],
        'tr' => ['label' => 'Türkçe', 'flag' => 'tr'],
        'it' => ['label' => 'Italiano', 'flag' => 'it'],
        'ar' => ['label' => 'العربية', 'flag' => 'xx', 'flag_overrides' => ['sa' => 'sa', 'eg' => 'eg', 'ae' => 'ae', 'ma' => 'ma', 'dz' => 'dz', 'tn' => 'tn', 'jo' => 'jo', 'ps' => 'ps', 'lb' => 'lb', 'iq' => 'iq', 'kw' => 'kw', 'qa' => 'qa', 'bh' => 'bh', 'om' => 'om', 'ye' => 'ye', 'sy' => 'sy', 'ly' => 'ly', 'sd' => 'sd', 'mr' => 'mr', 'dj' => 'dj', 'km' => 'km', 'so' => 'so'], 'dir' => 'rtl'],
        'ru' => ['label' => 'Русский', 'flag' => 'ru'],
        'pl' => ['label' => 'Polski', 'flag' => 'pl'],
        'ja' => ['label' => '日本語', 'flag' => 'jp'],
        'ko' => ['label' => '한국어', 'flag' => 'kr'],
        'id' => ['label' => 'Bahasa Indonesia', 'flag' => 'id'],
        'vi' => ['label' => 'Tiếng Việt', 'flag' => 'vn'],
        'th' => ['label' => 'ไทย', 'flag' => 'th'],
        'hi' => ['label' => 'हिन्दी', 'flag' => 'in'],
        'uk' => ['label' => 'Українська', 'flag' => 'ua'],
        'sk' => ['label' => 'Slovenčina', 'flag' => 'sk'],
        'cs' => ['label' => 'Čeština', 'flag' => 'cz'],
        'ro' => ['label' => 'Română', 'flag' => 'ro'],
        'nl' => ['label' => 'Nederlands', 'flag' => 'nl'],
        'sv' => ['label' => 'Svenska', 'flag' => 'se'],
        'da' => ['label' => 'Dansk', 'flag' => 'dk'],
        'fi' => ['label' => 'Suomi', 'flag' => 'fi'],
        'no' => ['label' => 'Norsk', 'flag' => 'no'],
        'el' => ['label' => 'Ελληνικά', 'flag' => 'gr'],
        'hu' => ['label' => 'Magyar', 'flag' => 'hu'],
        'he' => ['label' => 'עברית', 'flag' => 'il', 'dir' => 'rtl'],
        'bg' => ['label' => 'Български', 'flag' => 'bg'],
        'hr' => ['label' => 'Hrvatski', 'flag' => 'hr'],
        'sr' => ['label' => 'Srpski', 'flag' => 'rs'],
    ],
    'lang_search' => true,
    'site_name' => 'AI Opensubtitles',
    'api_key' => '5MGRBWO9lHA023KPmVMaa0PoRYHqQKpK',
    'api_base' => '/ai-web/api/v1',
    'api_base_server' => 'https://ai.opensubtitles.com/ai-web/api/v1',
    'dev_proxy_upstream' => 'https://ai.opensubtitles.com',
    'user_agent' => 'aios v1',
    'pricing_cache_ttl' => 21600,
    'credit_usd_rate' => 0.01,
    'cache_dir' => dirname(__DIR__) . '/cache',
];
