<?php

return [
	'nav.transcribe' => 'Transkribieren',
	'nav.translate' => 'Übersetzen',
	'nav.search' => 'Suche',
	'nav.pricing' => 'Preise',
	'nav.dashboard' => 'Dashboard',
	'nav.login' => 'Anmelden',
	'nav.logout' => 'Abmelden',

	'dashboard.show_more' => 'Mehr anzeigen',
	'dashboard.more_error' => 'Weitere konnten nicht geladen werden.',
	'dashboard.payments' => 'Zahlungshistorie',
	'payments.none' => 'Noch keine Zahlungen erfasst.',
	'payments.error' => 'Zahlungshistorie konnte nicht geladen werden.',

	'job.detecting_language' => 'Sprache wird erkannt…',
	'job.language_detected' => 'Sprache erkannt:',
	'job.language_detect_failed' => 'Die Sprache konnte nicht automatisch erkannt werden. Bitte wähle sie manuell aus.',

	'home.title' => 'KI-Untertitel: Transkribieren & Übersetzen',
	'home.hero_line1' => 'Dein Video. Jede Sprache.',
	'home.hero_line2' => 'Untertitel von KI.',

	'search.title' => 'Untertitel suchen',
	'search.meta_description' => 'Untertitel für Filme und Serien in Dutzenden Sprachen finden und als SRT herunterladen. Suche kostenlos, ohne Konto.',
	'search.h1' => 'Untertitel suchen',
	'search.lead' => 'Finde Untertitel für jeden Film oder jede Serie in Dutzenden Sprachen. Die Suche ist kostenlos — zum Herunterladen braucht es ein kostenloses Konto.',
	'search.tab_subtitles' => 'Untertitel',
	'search.tab_features' => 'Filme & Serien',
	'search.placeholder_subtitles' => 'Nach Film- oder Episodennamen suchen…',
	'search.placeholder_features' => 'Film oder Serie finden…',
	'search.language' => 'Sprache',
	'search.type' => 'Typ',
	'search.type_all' => 'Alle Typen',
	'search.type_movie' => 'Filme',
	'search.type_episode' => 'Serienfolgen',
	'search.advanced' => 'Erweiterte Optionen',
	'search.imdb_id' => 'IMDb-ID (z. B. tt0133093)',
	'search.year' => 'Erscheinungsjahr',
	'search.submit' => 'Suchen',
	'search.searching' => 'Suche…',
	'search.results_title_subtitles' => 'Untertitel-Ergebnisse',
	'search.results_title_features' => 'Filme & Serien',
	'search.results_for' => 'Ergebnisse für',
	'search.found' => 'Ergebnisse',
	'search.page_of' => 'Seite',
	'search.of' => 'von',
	'search.prev' => 'Zurück',
	'search.next' => 'Weiter',
	'search.empty' => 'Keine Ergebnisse gefunden. Versuche eine andere Suche oder weniger Filter.',
	'search.error' => 'Suche fehlgeschlagen:',
	'search.find_subtitles' => 'Untertitel finden',
	'search.episodes_count' => 'Folgen',
	'search.subtitles_count' => 'Untertitel',
	'search.preview' => 'Vorschau',
	'search.download' => 'SRT herunterladen',
	'search.downloading' => 'Wird heruntergeladen…',
	'search.loading_preview' => 'Vorschau wird geladen…',
	'search.login_required' => 'Zum Herunterladen von Untertiteln anmelden.',
	'search.download_failed' => 'Download fehlgeschlagen:',
	'search.release' => 'Release',
	'search.downloads' => 'Downloads',
	'search.uploaded' => 'Hochgeladen',
	'search.by' => 'von',
	'search.on_demand' => 'Wird bei Download on demand von KI erzeugt.',
	'search.hearing_impaired' => 'HI',
	'search.ai_translated' => 'KI',
	'search.foreign_parts' => 'Nur fremdsprachige Teile',
	'search.trusted' => 'Vertrauenswürdig',
	'search.close' => 'Schließen',
];
