<?php

return [
	'nav.transcribe' => 'Transcribe',
	'nav.translate' => 'Translate',
	'nav.pricing' => 'Pricing',
	'nav.login' => 'Log in',
	'nav.logout' => 'Log out',

	'common.faq_title' => 'Frequently asked questions',

	'footer.main_site' => 'opensubtitles.com',

	'home.title' => 'AI Subtitle Transcription & Translation',
	'home.meta_description' => 'Generate subtitles from any video or audio with AI and translate subtitle files into dozens of languages. Try it instantly in your browser.',
	'home.hero_line1' => 'Your video. Any language.',
	'home.hero_line2' => 'Subtitles by AI.',
	'home.hero_sub' => 'Transcribe media and translate subtitle files instantly — powered by the AI API behind opensubtitles.com.',
	'home.cta_try' => 'Try it now',
	'home.cta_apps' => 'Get the app',
	'home.transcribe_card' => 'Turn video or audio into accurate subtitles automatically.',
	'home.translate_card' => 'Translate SRT and VTT files into dozens of languages.',
	'home.how_title' => 'How it works',
	'home.how_step1' => 'Drop in a media or subtitle file.',
	'home.how_step2' => 'AI transcribes or translates it.',
	'home.how_step3' => 'Download your subtitles.',
	'home.apps_title' => 'Need more power?',
	'home.apps_text' => 'The desktop app adds batch processing, offline workflows and more. This site is a live demo — the apps are the full experience.',
	'home.apps_cta' => 'Get the desktop app',
	'home.faq_title' => 'FAQ',
	'home.faq_q1' => 'Which file types are supported?',
	'home.faq_a1' => 'Media files are transcribed; subtitle files like SRT and VTT are translated. Everything else is handled for you automatically.',
	'home.faq_q2' => 'Do I need an account?',
	'home.faq_a2' => 'Yes — you use your opensubtitles.com account. Credits are shared across the website and the apps.',
	'home.faq_q3' => 'What are credits?',
	'home.faq_a3' => 'Credits are the pay-as-you-go currency for AI transcription and translation. See the pricing page.',

	'transcribe.title' => 'AI Transcription — Video & Audio to Subtitles',
	'transcribe.meta_description' => 'Automatically generate subtitles from video and audio files with AI. Fast, accurate, right in your browser.',
	'transcribe.h1' => 'AI Transcription',
	'transcribe.lead' => 'Upload a video or audio file and get accurate subtitles in minutes. Your file is converted locally — only the audio track is uploaded.',
	'transcribe.cta' => 'Transcribe a file',
	'transcribe.faq_q1' => 'What happens to my file?',
	'transcribe.faq_a1' => 'Media is converted to a mono MP3 in your browser; only that audio track is uploaded for transcription.',
	'transcribe.faq_q2' => 'Which formats work?',
	'transcribe.faq_a2' => 'Common video and audio formats are supported. You always receive SRT or VTT subtitles.',

	'translate.title' => 'AI Subtitle Translation — SRT & VTT',
	'translate.meta_description' => 'Translate subtitle files into dozens of languages with AI. Preserve timing, keep the meaning, done in your browser.',
	'translate.h1' => 'AI Subtitle Translation',
	'translate.lead' => 'Upload an SRT or VTT file, pick a target language, and let AI translate it while keeping your timing intact.',
	'translate.cta' => 'Translate a subtitle file',
	'translate.faq_q1' => 'Which subtitle formats?',
	'translate.faq_a1' => 'SRT and VTT are the standard output formats; more input formats are supported.',
	'translate.faq_q2' => 'Will the timing change?',
	'translate.faq_a2' => 'No — timestamps are preserved exactly. Only the text is translated.',

	'pricing.title' => 'Pricing — AI Model Prices',
	'pricing.meta_description' => 'Transparent pay-as-you-go prices for AI subtitle transcription and translation models.',
	'pricing.h1' => 'Model prices',
	'pricing.lead' => 'Pay as you go with credits — the same prices on the website and in all apps.',
	'pricing.transcription' => 'Transcription',
	'pricing.translation' => 'Translation',
	'pricing.languages' => 'languages',
	'pricing.empty' => 'Prices are being loaded — check back shortly.',

	'login.title' => 'Log in',
	'login.meta_description' => 'Log in with your opensubtitles.com account.',
	'login.h1' => 'Log in',
	'login.username' => 'Username',
	'login.password' => 'Password',
	'login.remember' => 'Remember me',
	'login.expired' => 'Your session has expired. Please log in again.',
	'login.submit' => 'Log in',
	'login.register_hint' => 'No account yet?',
	'login.register_link' => 'Register on opensubtitles.com',

	'dashboard.title' => 'Dashboard',
	'dashboard.h1' => 'Dashboard',
	'dashboard.credits' => 'Your credits',
	'dashboard.new_job' => 'New job',
	'dashboard.new_job_cta' => 'Upload a file',
	'dashboard.recent' => 'Recent activities',
	'dashboard.media' => 'Recent media',

	'job.new_title' => 'New job',
	'job.new_h1' => 'New job',
	'job.new_lead' => 'Drop a media file for transcription or a subtitle file (SRT/VTT) for translation — the format is detected automatically.',
	'job.drop_hint' => 'Drop a file here or click to choose',
	'job.transcription_options' => 'Transcription',
	'job.translation_options' => 'Translation',
	'job.model' => 'Model',
	'job.language' => 'Language',
	'job.from' => 'Translate from',
	'job.to' => 'Translate to',
	'job.submit' => 'Start job',
	'job.converting' => 'Converting to mono MP3…',
	'job.uploading' => 'Uploading…',
	'job.list_title' => 'Your jobs',
	'job.list_h1' => 'Your jobs',
	'job.list_empty' => 'No jobs yet — upload a file to get started.',
	'job.status_title' => 'Job status',
	'job.status_h1' => 'Job status',
	'job.file' => 'File',
	'job.credits_used' => 'Credits used',
	'job.credits_left' => 'Credits left',
	'job.download' => 'Download subtitles',
	'job.readability' => 'Readability',

	'read.captions' => 'Captions',
	'read.analyzed' => 'Analyzed',
	'read.avg_speed' => 'Avg speed',
	'read.max_speed' => 'Max speed',
	'read.longest_line' => 'Longest line',
	'read.limits' => 'Limits',
	'read.chars' => 'chars',
	'read.chars_line' => 'chars/line',
	'read.lines' => 'lines',
	'read.no_problems' => 'No readability issues — this subtitle is comfortable to read.',
	'read.issues_total' => 'readability issue(s) found:',
	'read.more_not_shown' => 'further issues not shown',
	'read.limit' => 'limit',
	'read.reading_speed' => 'Reading speed',
	'read.line_length' => 'Line length',
	'read.line_count' => 'Line count',
];
